version: '3.8'

services:
  eureka:
    image: kdh19/eureka:latest
    container_name: eureka_container
    restart: always
    ports:
      - "8761:8761"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 15s # Eureka가 부팅될 시간을 확보

  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Book
      MYSQL_USER: springboot
      MYSQL_PASSWORD: p@ssw0rd
    ports:
      - "3308:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    image: kdh19/springimg:0.0.8
#    container_name: backend_container

    restart: always
    depends_on:
      mysql:
        condition: service_healthy  # MySQL이 정상적으로 실행된 후 시작
      eureka:
        condition: service_healthy  # Eureka가 시작된 후 실행
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Book?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: springboot
      SPRING_DATASOURCE_PASSWORD: p@ssw0rd
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/  # Eureka 서버 주소 추가
    ports:
      - "8090:8090"
    networks:
      - my_network

  front:
    image: jjabc3758/sports-news:0.0.4
    container_name: front_container
    restart: always
    depends_on:
      - backend
    ports:
      - "1000:80"  # React 앱 기본 포트
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql_data:

